#########################################################################
# Dependabot configuration file
#########################################################################

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00" # UTC

  ###################################
  # golang workspace  ###############
  ###################################
  - package-ecosystem: gomod
    directory: /src
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00" # UTC

  ###################################
  # Poetry  #########################
  ###################################
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00" # UTC
    versioning-strategy: increase
