name: build

on:
  workflow_call:
    inputs:
      pinned_image:
        required: true
        type: string
    outputs:
      artifact-url:
        description: "URL of the uploaded build artifact"
        value: ${{ jobs.build.outputs.artifact-url }}
      artifact-id:
        description: "id of the uploaded build artifact"
        value: ${{ jobs.build.outputs.artifact-id }}
    secrets:
      SONAR_TOKEN:
        required: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.pinned_image }}
      options: --user 1001:1001 --group-add 128
    defaults:
      run:
        shell: bash
    outputs:
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: copy .tool-versions
        run: |
          cp /home/vscode/.tool-versions "$HOME/.tool-versions"
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: make install
        run: |
          make install

      - name: run compile-go
        run: make compile-go

      - name: Upload build artifact
        id: upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: packaged_code
          path: |
            lib/get-secrets-layer.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged_code_arm
          path: |
            lib/get-secrets-layer-arm.zip
